# Generated by Django 6.0.6 on 2026-07-01 15:38

import django.db.models.deletion
import reportador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Cliente')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('administrador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inspeccion', models.CharField(max_length=50, unique=True, verbose_name='ID Inspección')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('administrador', models.CharField(max_length=150, verbose_name='Administrador')),
                ('supervisor', models.CharField(default='Nicolas Gaviria Gonzalez', max_length=150, verbose_name='Supervisor')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('enfoque', models.CharField(choices=[('Aseo y Limpieza', 'Aseo y Limpieza'), ('Seguridad y Salud en el Trabajo', 'Seguridad y Salud en el Trabajo'), ('Colaborador', 'Colaborador'), ('Otros', 'Otros')], max_length=100, verbose_name='Enfoque de la inspección')),
                ('concepto', models.CharField(choices=[('Zonas comunes', 'Zonas comunes'), ('Ascensores', 'Ascensores'), ('Paredes', 'Paredes'), ('Pasamanos', 'Pasamanos'), ('Escalas', 'Escalas'), ('Zonas verdes', 'Zonas verdes'), ('Otros', 'Otros')], max_length=100, verbose_name='Concepto Técnico')),
                ('calificacion', models.CharField(choices=[('Excelente', 'Excelente'), ('Regular', 'Regular'), ('Mala', 'Mala')], max_length=20, verbose_name='Calificación')),
                ('observacion', models.TextField(verbose_name='Observación')),
                ('conclusion', models.TextField(verbose_name='Conclusión General')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones', to='reportador.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Inspección',
                'verbose_name_plural': 'Inspecciones',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='InspeccionEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=reportador.models.path_evidencias, verbose_name='Evidencia (Foto/Video)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='reportador.inspeccion')),
            ],
            options={
                'verbose_name': 'Evidencia de Inspección',
                'verbose_name_plural': 'Evidencias de Inspecciones',
            },
        ),
        migrations.CreateModel(
            name='ClienteCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=150, verbose_name='Correo Electrónico')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos_contacto', to='reportador.cliente')),
            ],
            options={
                'verbose_name': 'Correo de Cliente',
                'verbose_name_plural': 'Correos de Clientes',
                'unique_together': {('cliente', 'correo')},
            },
        ),
    ]
