# Generated by Django 6.0.6 on 2026-07-02 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspeccion',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='enfoque',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='inspeccionevidencia',
            name='inspeccion',
        ),
        migrations.CreateModel(
            name='InspeccionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfoque', models.CharField(choices=[('Aseo y Limpieza', 'Aseo y Limpieza'), ('Seguridad y Salud en el Trabajo', 'Seguridad y Salud en el Trabajo'), ('Colaborador', 'Colaborador'), ('Otros', 'Otros')], max_length=100, verbose_name='Enfoque de la inspección')),
                ('concepto', models.CharField(choices=[('Zonas comunes', 'Zonas comunes'), ('Ascensores', 'Ascensores'), ('Paredes', 'Paredes'), ('Pasamanos', 'Pasamanos'), ('Escalas', 'Escalas'), ('Zonas verdes', 'Zonas verdes'), ('Otros', 'Otros')], max_length=100, verbose_name='Concepto Técnico')),
                ('calificacion', models.CharField(choices=[('Excelente', 'Excelente'), ('Regular', 'Regular'), ('Mala', 'Mala')], max_length=20, verbose_name='Calificación')),
                ('observacion', models.TextField(verbose_name='Observación')),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='reportador.inspeccion')),
            ],
            options={
                'verbose_name': 'Detalle de Inspección',
                'verbose_name_plural': 'Detalles de Inspecciones',
            },
        ),
        migrations.AddField(
            model_name='inspeccionevidencia',
            name='detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='reportador.inspecciondetalle'),
        ),
    ]
