# Generated by Django 6.0.6 on 2026-07-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportador', '0002_remove_inspeccion_calificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspeccion',
            name='id_inspeccion',
        ),
    ]
