# Generated by Django 5.1.11 on 2026-07-17 16:56

import django.db.models.deletion
import reportador.models
import roka.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportador', '0004_rename_created_at_inspeccion_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccionevidencia',
            name='archivo',
            field=models.FileField(max_length=255, storage=roka.storage_backends.EvidenciasStorage, upload_to=reportador.models.path_evidencias, verbose_name='Evidencia (Foto/Video)'),
        ),
        migrations.AlterField(
            model_name='inspeccionevidencia',
            name='detalle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='reportador.inspecciondetalle'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PDFInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=255, storage=roka.storage_backends.PDFInspeccionesStorage, upload_to=reportador.models.pdf_inspeccion_path)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('enviado', models.BooleanField(default=False)),
                ('inspeccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='reportador.inspeccion')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
