# Generated by Django 6.0.6 on 2026-07-08 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportador', '0004_rename_created_at_inspeccion_fecha_creacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la reunión')),
                ('hora', models.TimeField(verbose_name='Hora de la reunión')),
                ('supervisor', models.CharField(max_length=150, verbose_name='Supervisor')),
                ('notas', models.TextField(verbose_name='Notas de la reunión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reuniones', to='reportador.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reuniones_prestacion_servicios', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Reunión',
                'verbose_name_plural': 'Reuniones',
                'db_table': 'reuniones_prestacion_servicios',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
