# Generated by Django 6.0.6 on 2026-07-10 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportador', '0004_rename_created_at_inspeccion_fecha_creacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidadoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('conclusion_general', models.TextField(blank=True, verbose_name='Conclusión General')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidados_generados', to=settings.AUTH_USER_MODEL, verbose_name='Generado por (Administrador)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidados', to='reportador.cliente', verbose_name='Cliente')),
                ('inspecciones', models.ManyToManyField(related_name='consolidados', to='reportador.inspeccion', verbose_name='Inspecciones Incluidas')),
            ],
            options={
                'verbose_name': 'Consolidado de Cliente',
                'verbose_name_plural': 'Consolidados de Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
