# Generated by Django 5.1.11 on 2026-07-17 16:56

import admin_roka.models
import django.db.models.deletion
import roka.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_roka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidadocliente',
            name='tipo',
            field=models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual'), ('PERSONALIZADO', 'Personalizado')], default='PERSONALIZADO', max_length=20),
        ),
        migrations.CreateModel(
            name='PDFConsolidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=255, storage=roka.storage_backends.PDFConsolidadosStorage, upload_to=admin_roka.models.pdf_consolidado_path)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('enviado', models.BooleanField(default=False)),
                ('consolidado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='admin_roka.consolidadocliente')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
