name: Deploy RokaSAS Django

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Marcar directorio como seguro en Git
        run: git config --global --add safe.directory /var/www/rokasas

      - name: Actualizar código
        run: |
          cd /var/www/rokasas
          git fetch origin
          git reset --hard origin/main

      - name: Instalar dependencias
        run: |
          cd /var/www/rokasas
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Verificar Django
        run: |
          cd /var/www/rokasas
          source venv/bin/activate
          python manage.py check

      - name: Ejecutar migraciones
        run: |
          cd /var/www/rokasas
          source venv/bin/activate
          python manage.py migrate --noinput

      - name: Compilar Tailwind CSS
        run: |
          cd /var/www/rokasas
          source venv/bin/activate
          python manage.py tailwind build

      - name: Actualizar archivos estáticos
        run: |
          cd /var/www/rokasas
          source venv/bin/activate
          python manage.py collectstatic --noinput

      - name: Reiniciar PM2 y Apache
        run: |
          /usr/bin/pm2 restart rokasas
          sudo systemctl reload httpd